import './globals.css'
import { Roboto } from 'next/font/google'
import '@fontsource/roboto/300.css';

const inter = Roboto({ subsets: ['latin'], weight:'300'})


export const metadata = {
  title: 'Mi blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
